version: '3.7'
networks:
    twitter_dev:
        name: twitter_dev
        driver: bridge
services:
    postgres:
        image: postgres
        ports:
            - "6432:5432"
        env_file: .env
        networks:
            - twitter_dev
    ums:
        image: twitter_lab/ums:latest
        ports:
            -   9000:9000
        networks:
            - twitter_dev
    twitter:
        image: twitter_lab/twitter:latest
        ports:
            -   9001:9001
        networks:
            - twitter_dev
