version: '3.7'
networks:
    twitter_dev:
        name: twitter_dev
        driver: bridge
services:
    postgres:
        image: postgres
        ports:
            - "6432:5432"
        env_file: .env
        networks:
            - twitter_dev
    ums:
        image: openjdk
        env_file: .env
        entrypoint: 'java -jar /home/ums/build/libs/ums-1.2.jar'
        ports:
            -   9000:9000
        volumes:
            -   '$PWD:/home/'
        networks:
            - twitter_dev
    twitter:
        image: openjdk
        env_file: .env
        entrypoint: 'java -jar /home/twitter/build/libs/twitter-1.2.jar'
        ports:
            -   9001:9001
        volumes:
            -   '$PWD:/home/'
        networks:
            - twitter_dev
