## Server
server:
  port: 9001

## MySQL
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_CONNECTION}/twitter
    username: postgres
    password: ${POSTGRES_PASSWORD}

ums:
  host: ${UMS_APP}
  port: 9000
  paths:
    user: /users/user

