## Server
server:
  port: 9000

## PgSQL
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_CONNECTION}/ums
    username: postgres
    password: ${POSTGRES_PASSWORD}
