kind: Service
apiVersion: v1
metadata:
    name: twitter
    namespace: default
    labels:
        app: twitter
spec:
    ports:
        - protocol: TCP
          port: 9001
          targetPort: 9001
          nodePort: 32001
    selector:
        app: twitter
    type: NodePort