kind: Service
apiVersion: v1
metadata:
    name: ums
    namespace: default
    labels:
        app: ums
spec:
    ports:
        - protocol: TCP
          port: 9000
          targetPort: 9000
          nodePort: 32000
    selector:
        app: ums
    type: NodePort