apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: ums
    namespace: default
spec:
    maxReplicas: 12
    metrics:
        - resource:
              name: cpu
              target:
                  averageUtilization: 30
                  type: Utilization
          type: Resource
    minReplicas: 2
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: ums